export type ValidSkills =
  | "AI"
  | "Voice"
  | "Automation"
  | "LLM"
  | "Chatbot"
  | "NLP"
  | "FPGA"
  | "Verilog"
  | "Cryptography"
  | "DE10"
  | "VGA"
  | "DE1-SoC"
  | "MATLAB"
  | "Machine Learning"
  | "Predictive Maintenance"
  | "Research"
  | "Signal Processing"
  | "Acoustics"
  | "Digital Design"
  | "Hardware"
  | "CPU"
  | "C++"
  | "Raylib"
  | "Game Dev"
  | "n8n"
  | "AI Agents"
  | "Workflow Automation"
  | "Voice AI"
  | "Chatbot Development"
  | "C/C++"
  | "Assembly"
  | "Intel DE1-SoC"
  | "Quartus"
  | "ModelSim"
  | "RTL Design"
  | "Arduino"
  | "Proteus"
  | "Multisim"
  | "AutoCAD"
  | "PSpice"
  | "LabVIEW"
  | "Atmel Studio"
  | "Digital Logic"
  | "Computer Architecture"
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Framer Motion"
  | "Kotlin"
  | "Android Studio"
  | "RESTful APIs"
  | "x86 Assembly"
  | "OpenGL/Glut"
  | "Data Structures"
  | "OOP"
  | "Operating Systems"
  | "Database Systems"
  | "Computer Networks"
  | "Cybersecurity"
  | "Community Service"
  | "Workshop Facilitation"
  | "Scratch"
  | "Backend"
  | "Java Swing"
  | "OpenAI API"
  | "POSIX"
  | "Semaphores"
  | "Mutex"
  | "SFML"
  | "OpenGL";

export type ValidCategory =
  | "AI"
  | "Voice"
  | "Automation"
  | "LLM"
  | "Chatbot"
  | "NLP"
  | "FPGA"
  | "Verilog"
  | "Cryptography"
  | "DE10"
  | "VGA"
  | "DE1-SoC"
  | "MATLAB"
  | "Machine Learning"
  | "Predictive Maintenance"
  | "Research"
  | "Signal Processing"
  | "Acoustics"
  | "Digital Design"
  | "Hardware"
  | "CPU"
  | "C++"
  | "Raylib"
  | "Game Dev"
  | "Full Stack"
  | "Frontend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Backend"
  | "3D Modeling"
  | "Android"
  | "Cybersecurity"
  | "Desktop App"
  | "Systems"
  | "Database";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
