export const siteConfig = {
  name: "Ibraheem Aziz - Computer Science Portfolio",
  brandName: "Ibraheem Aziz",
  subtitle: "Computer Science Student at FAST NUCES",
  tagline: "Computer Science Portfolio",
  authorName: "Ibraheem Aziz",
  username: "ibraheem-aziz",
  location: "Rawalpindi, Pakistan",
  email: "ibraheemaziz3568@gmail.com",
  secondaryEmail: "",
  phone: "+92 332 8540999",
  website: "ibraheems-cv-website.vercel.app",
  description:
    "Computer Science student focused on full-stack, mobile, backend, and cybersecurity systems.",
  url: "https://ibraheems-cv-website.vercel.app",
  links: {
    linkedin: "https://www.linkedin.com/in/ibraheem-aziz-693b19322/",
    github: "https://github.com/1braheem",
  },
  ogImage: "/ibraheem-profile.jpg",
  iconIco: "/ibraheem-profile.jpg",
  logoIcon: "/ibraheem-profile.jpg",
  profileImage: "/ibraheem-profile.jpg",
  keywords: [
    "Ibraheem Aziz",
    "Computer Science Student",
    "Software Engineering Intern",
    "Backend Development",
    "Cybersecurity",
    "Android Development",
    "Kotlin",
    "PHP",
    "MySQL",
    "C++",
    "Python",
    "Java",
    "Docker",
    "FAST NUCES",
    "Rawalpindi Pakistan",
  ],
};
